linux_task:
  container:
    image: gcc:latest
    cpu: 8
    memory: 24
  setup_script:
    - git fetch --tags
  configure_script:
    - ./configure
  compile_script:
    - make all modules
  test_script:
    - make check

macos_task:
  osx_instance:
    image: mojave-base
  setup_script:
    - git fetch --tags
  configure_script:
    - ./configure
  compile_script:
    - make all modules
  test_script:
    - make check

freebsd_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  setup_script:
    - pkg install -y git
    - git fetch --tags
  configure_script:
    - ./configure
  compile_script:
    - make all modules
  test_script:
    - make check
