linux_task:
  container:
    image: gcc:latest
    cpu: 8
    memory: 24
  setup_script:
    - git fetch --tags
  configure_script:
    - ./configure
  compile_script:
    - make -j all modules
  test_script:
    - make check
