linux_task:
  container:
    image: gcc:latest
    cpu: 8
    memory: 24
  setup_script:
    - git fetch --tags
  configure_script:
    - ./configure
  compile_script:
    - make all modules
  test_script:
    - make check

macos_task:
  osx_instance:
    image: mojave-base
  setup_script:
    - git fetch --tags
  configure_script:
    - ./configure
  compile_script:
    - make all modules
  test_script:
    - make check

freebsd_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  setup_script:
    - pkg install -y git
    - git fetch --tags
  configure_script:
    - ./configure
      --prefix=$HOME/.gambit_builds/$CIRRUS_BRANCH
      --enable-gambitdir=~/.gambit_builds/$CIRRUS_BRANCH
  compile_script:
    - make all modules
  test_script:
    - make check
  snapshot_script:
    - make install
    - tar -czf /gambit-$CIRRUS_BRANCH.tgz $HOME/.gambit_builds/$CIRRUS_BRANCH/
  binaries_artifacts:
    path: "/gambit-*.tgz"

cygwin_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  setup_script:
    - choco install -y --no-progress cygwin
    - c:\tools\cygwin\cygwinsetup -q -P binutils,gcc-core,make
    - git fetch --tags
  configure_script:
    - c:\tools\cygwin\bin\bash --login "%CD%\ci\cygwin.sh" configure
  compile_script:
    - c:\tools\cygwin\bin\bash --login "%CD%\ci\cygwin.sh" compile
  test_script:
    - c:\tools\cygwin\bin\bash --login "%CD%\ci\cygwin.sh" test

msvc_task:
  windows_container:
    dockerfile: ci/Dockerfile.msvc
    os_version: 2019
  setup_script:
    - git fetch --tags
  configure_script:
    - which cl make
